services:
    frontend:
        build: ./frontend
        ports:
            - '5173:5173'
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - '5000:5000'
        depends_on:
            - redis
        env_file: .env
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - HOST=0.0.0.0

    redis:
        image: redis
        ports:
            - '6379:6379'
